### ISSUE TITLE
Record Cursor Character Position

### ISSUE THREAD

**Issue by krausekai** [heycalmdown/navigate-cursor-history#2]
Thanks for the plugin!

In addition to `cursor.line`, I request that `cursor.ch` should be recorded from `editor.getCursor("head")`:

https://github.com/heycalmdown/navigate-cursor-history/blob/ea9a34f3296420abb2d4b846fd67b4bc7cef2535/main.ts#L69

This would be more consistent with behavior found in other (code) editor apps.

**Comment by heycalmdown** [comment]
https://github.com/heycalmdown/navigate-cursor-history/commit/2b64c5e7c7920f8e1267fd45f135737b5260fba7
